cmake_minimum_required(VERSION 4.1)
project(proiect1)

set(CMAKE_CXX_STANDARD 20)

add_executable(proiect1 main.cpp
        Item.cpp
        Item.h
        Echipament.h
        ConsumabilBase.h
        Itemspecial.cpp
        Itemspecial.h
        Arma.cpp
        Arma.h
        Armura.cpp
        Armura.h
        Consumabil.cpp
        Consumabil.h
        Magie.cpp
        Magie.h
        Exceptii.h
        Inventar.h
        Player.cpp
        Player.h
        Meniu.cpp
        Meniu.h
        MagicItem.h
        Topor.h
        Scut.h
        Potiune.h
        Hrana.h
        Exceptions.h
        Inventar.cpp)
